### ISSUE TITLE
Run mysqldump without slow down the server

### ISSUE THREAD

**Issue by gabrielkoerich** [backup-manager/backup-manager#102]
Hey, is it possible to pass parameters to mysqldump?

I'm using backup-manager in a production server and mysqldump slows it down.

I found [this](http://stackoverflow.com/questions/5666784/how-can-i-slow-down-a-mysql-dump-as-to-not-affect-current-load-on-the-server) thread in stackoverflow, saying that I need to use the --single-transaction and --quick options for mysqldump on innodb. 

Is there an option to add this parameters? Thanks.

**Comment by sune-sporti** [comment]
Is it a large database? Like 2-3+ GB? I had this problem, where the server was very slow for 3-4 minutes while the backup ran. My solution was to make a new slave DB server where the backup-manager is running a backup on the replicated database on the DB slave server. And now the production server have absolutly no downtime at all.

**Comment by gabrielkoerich** [comment]
Yep. I endup rewriting the MysqlDatabase class to accept more arguments:

```php
$command = sprintf('mysqldump --routines --host=%s --port=%s --user=%s --password=%s %s > %s %s',
            escapeshellarg($this->config['host']),
            escapeshellarg($this->config['port']),
            escapeshellarg($this->config['user']),
            escapeshellarg($this->config['pass']),
            escapeshellarg($this->config['database']),
            escapeshellarg($outputPath),
            $this->config['arguments']
);
```

So I'm passing the options `--single-transaction --quick --lock-tables=false` now.

I'll try to create a pull request later if I have time.

**Comment by ShawnMcCool** [comment]
I saw a solid pull request on this subject. It should fix it. I'm close to merging it in.

**Comment by mfaatz** [comment]
You know what would be awesomer?  Add a new "options" parameter (the above request) before the db parameter, and add a new last parameter we can stuff table names into so we can backup just specific tables!
