### ISSUE TITLE
Split dump into files for each table

### ISSUE THREAD

**Issue by sune-sporti** [backup-manager/backup-manager#103]
It could be a nice feature to be able to backup (and restore) into files for each table in the database. That would make it easy to find a subset of data if you get into troubles. Especially for large databases. :-)

**Comment by dhcmega** [comment]
Totally agree.
I think that even to have one big gzip file is not good. I would create a gzip file for files and the one file per table, it can all be organized with directories.
That is how I am doing it with a bash script, I would like to take it a new level using something more fun, as laravel.

**Comment by ShawnMcCool** [comment]
Sounds like you need to select a list of all tables, then for each table run a mysql_dump command, compress them individually, then upload them individually.
