### ISSUE TITLE
Dropbox problem when overwriting files

### ISSUE THREAD

**Issue by khrizt** [backup-manager/backup-manager#104]
Hi,

I'm trying to save my backups in dropbox but when run the backup the second time I get this error:

```
[League\Flysystem\FileExistsException]         
File already exists at path: database.sql.gz  
```

Is there a way to set that the file must be overwritten in the dropbox folder?

**Comment by ArtemProkopenko** [comment]
+1

**Comment by omurphy27** [comment]
+1

Would be very nice to have this feature

**Comment by omurphy27** [comment]
Just implemented a quick and dirty fix which seems to do the trick. 

In this file: `/vendor/backup-manager/backup-manager/src/Tasks/Storage/TransferFile.php`

Change the execute function to below:

`/**
     * @throws \InvalidArgumentException
     */
    public function execute() {

        // if File already exists, then delete before writing again
        if ( $this->destinationFilesystem->has( $this->destinationPath ) ) {
            $this->destinationFilesystem->delete( $this->destinationPath );
        } 

        $this->destinationFilesystem->writeStream(
            $this->destinationPath,
            $this->sourceFilesystem->readStream($this->sourcePath)
        );
            
    }`

Seems to be working fine when saving to local and Dropbox.

**Comment by lenamtl** [comment]
+1 Thanks

**Comment by ShawnMcCool** [comment]
I'm not sure that people would appreciate their files being deleted. Why not just save the file as a new name that doesn't already exist?

**Comment by lenamtl** [comment]
Maybe having both option as a setting ...

**Comment by ShawnMcCool** [comment]
There's a delete file task already. It's composable and can be used to create a new procedure, for example.. OverwriteBackupProcedure.

You could copy this file: https://github.com/backup-manager/backup-manager/blob/master/src/Procedures/BackupProcedure.php

Then, add a deletefile task. Or inject whatever task you want.

**Comment by antonioribeiro** [comment]
1) Every 2 hours (I keep them forever). Naming system:

```
https://s3.amazonaws.com/<bucket>/backup/databases/hourly/2017/04/25/namespace.domain.com.database_name.2017-04-25T17-44-28.connection_name.backup.sql.gz
```

2) Every 15 minutes (I overwrite them, it's just a failsafe with a shorter timeframe). Naming system:

```
https://s3.amazonaws.com/<bucket>/backup/databases/minutely/namespace.domain.com.database_name.connection_name.backup.sql.gz
```
