### ISSUE TITLE
[Suggestion] Ignoring certain tables

### ISSUE THREAD

**Issue by hiendv** [backup-manager/backup-manager#106]
Hi, I'm working on MySQL databases whose some tables shouldn't be included. So, any plans for supporting e.g `--ignore-table` in MySQL `mysqldump`?
Thank you !

**Comment by zach-adams** [comment]
Just FYI you can clone the Database class and add your own parameters including --ignore-tables and also only including certain tables:

https://gist.github.com/zach-adams/5c32775bf6c38c0988750c4ca9aab50f
