### ISSUE TITLE
Dynamic connections

### ISSUE THREAD

**Issue by digixweb** [backup-manager/backup-manager#108]
I was wondering if it is somehow possible to utilize this package for dynamic connections. I have several databases which I currently don't define inside the database.php conf file, but are dynamically approached based on the user credentials when they log in. So the database settings are defined inside a database as well. It would be great if I could loop through all the users and populate the laravel scheduler with these credentials to create the individual backups.

**Comment by ShawnMcCool** [comment]
I see that Config should be an interface and there should be a specific php file implementation.

You can create a config class of your own, extend the backup manager's, and override the public functions with your own.
