### ISSUE TITLE
Backup a remote server

### ISSUE THREAD

**Issue by ronlinet** [backup-manager/backup-manager#111]
Hi Guys, 
My scenario is to run backup manager from a workstation in my office which will connect and backup a remote server through the ssh.  
I see in configuration that we can backup a remote database but I don't see the part where we should put an IP to backup a remote files system / server. Is there such an option ?
Thx.

**Comment by m0k1** [comment]
https://github.com/backup-manager/backup-manager/blob/master/examples/standalone/config/database.php#L6
