### ISSUE TITLE
postgresql --clean option when dumping database

### ISSUE THREAD

**Issue by godeg123** [backup-manager/backup-manager#114]
can you add --clean option to postgresql dump command as shown this image

![screenshot at 16-10-42](https://cloud.githubusercontent.com/assets/12759680/18742729/04fe6bfc-80e0-11e6-91eb-93bc31ba4ddc.png)

thank you.

**Comment by ShawnMcCool** [comment]
Hello, I'm currently spread over a few projects pretty heavily right now. I'm not super experienced with Postgresql. Can you tell me what this does and perhaps implement it in a pull request (minor test updates are probably necessary) and send it in?

**Comment by godeg123** [comment]
referring to this help command output, "it clean (drop) database objects before recreating".

ok will try create pull request for this..

thanks

![screenshot at 13-43-38](https://cloud.githubusercontent.com/assets/12759680/21515612/da9489c6-cd03-11e6-9697-b52df3f9ad40.png)
