### ISSUE TITLE
Specify Tables to back up

### ISSUE THREAD

**Issue by mfaatz** [backup-manager/backup-manager#118]
It would be great to be able to specify a subset of tables to back up.

Reason: My laravel website has a bunch of migrations that might change with releases for the 'factory' tables, so it would be nice to be able to refresh migrations, while having a separate backup and restore of posts/tags/category tables.

**Comment by ShawnMcCool** [comment]
It's relatively new, but we currently have an 'ignore tables' list.

**Comment by antonioribeiro** [comment]
About specifying tables names: `--database` give us the impression of being "datatabase name", but it is actually "connection", so as I'm needing to change the database name (to use the same connection to backup many different databases), would you accept a `--databaseName` [pull request](https://github.com/antonioribeiro/backup-manager/commit/532da2805ef94cbe0073dcd32bc33e1edab01ada
)?

Ideally it should be changed to `--connection` and `--database`, but this would be a breaking change...

**Comment by ShawnMcCool** [comment]
Agreed. The code needs to be updated, documentation needs to be changed, and then we need to tag a new major version.
