### ISSUE TITLE
mysqldump uses wrong syntax for ignored tables

### ISSUE THREAD

**Issue by cklm** [backup-manager/backup-manager#125]
This functions seems to be wrong: https://github.com/backup-manager/backup-manager/blob/4c10b9d28e4a5aaedc7439d121c00e64b97b0dc4/src/Databases/MysqlDatabase.php#L76

The MySQL-Manual says, `To ignore multiple tables, use this option multiple times.` [Link to manual](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_ignore-table) which seems to be right, since the comma-separated list is not working for me (given tables are not ignored). Can someone verify that?

**Comment by ShawnMcCool** [comment]
Thanks for bringing this up. If you get a chance to test it and submit a PR it'd be appreciated.
