### ISSUE TITLE
Support no password for when password is empty

### ISSUE THREAD

**Issue by isometriq** [backup-manager/backup-manager#128]
When using user "root" no password on database (on local development of course), if get this error:
```
  [BackupManager\ShellProcessing\ShellProcessFailed]
  mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: YES)" when trying to connect
```

To fix this, the `mysqldump` call should not use the `-p` flag at all when password is empty.

Do you accept pull requests?

**Comment by ShawnMcCool** [comment]
We definitely accept pull requests. =) Please ensure that the feature is tested.
