### ISSUE TITLE
What if Server Space is full or DB is Down

### ISSUE THREAD

**Issue by nitin19srivastava** [backup-manager/backup-manager#130]
hi,

I have set up a cron job, for DB backup and storing in project directory.

I need to know, what will happen:
    1) - If Server space is full.
    2) - DB is down.

How i will come to know whether the backup is success or failure.?

Secondly - how to add labels to issue.? eg-  this is question. how to tag with question label.?

**Comment by ShawnMcCool** [comment]
I'm not sure what happens in these cases. I'd be open to someone testing and reporting in. We could come up with a solution and work to get it in.

**Comment by nitin19srivastava** [comment]
Thanks @ShawnMcCool , please come up fast with the solution.

**Comment by ShawnMcCool** [comment]
I'm not going to create a solution. If someone wants to experiment and provide information here, then they or someone else might chime in and provide some insights, which someone might turn into a pull request, which will be reviewed and merged.

**Comment by armandsar** [comment]
Experienced this recently. 
You are gonna get 
BackupManager\ShellProcessing\ShellProcessFailed: 
gzip: path/5972bfb15fae1.gz: No space left on device

**Comment by nitin19srivastava** [comment]
@armandsar Can you share your code, how you caught the exception.?      I have set Cron Job, for DB backup.  My Code is - `    public function backup(){
        $env=production;
        $destination='local';
        $file_name=Carbon::now()->timestamp;
        $compression='gzip';
    	$manager = require 'frame/bootstrap/bootstrap.php';
        $manager->makeBackup()->run($env, [new Destination($destination, $file_name)], $compression);
    }`
How to catch exception.?

**Comment by nitin19srivastava** [comment]
What is Google cs.?  how to backup on that.?   'gcs' => [
        'type' => 'Gcs',
        'key'    => '',
        'secret' => '',
        'bucket' => '',
        'root'   => '',
    ],

**Comment by ShawnMcCool** [comment]
@nitin19srivastava re-reading your original post. I think that you can just catch Exceptions and have a good idea if something failed.

**Comment by nitin19srivastava** [comment]
@ShawnMcCool How to catch Exception.?

`$db_backup = $manager->makeBackup()->run($env, [new Destination($destination, $file_name)], $compression);

        if($db_backup != null){
            $response=response()->json(['message'=>$db_backup,'status'=>0]);
        }
        else{
            $db_backup='Database Backup Done';
            $response=response()->json(['message'=>$db_backup,'status'=>1]);
        }

        app('sneaker')->captureException(new Exception($response));
`

is this way correct.?  i am reading the response in a variable.  i backup done , then variable is null else the error comes in variable.  Then i am mailing to self, using another package.

**Comment by ShawnMcCool** [comment]
Are you familiar with the idea of exceptions, try, and catch in PHP? It's 100% necessary in order to do what you want to do.

http://php.net/manual/en/language.exceptions.php
