### ISSUE TITLE
Upload to Special Cloud with WebDAV

### ISSUE THREAD

**Issue by emresaracoglu** [backup-manager/backup-manager#132]
Hello

Do we have a chance to upload to a private server with WebDAV?

**Comment by Nyholm** [comment]
Could you elaborate please?

Btw, we use Flysystem that handles all the uploads.

**Comment by ShawnMcCool** [comment]
@emresaracoglu If you help the Flysystem package support more storage types, that'd be best. If you'd like to respond to this issue please do. But, since it's quite old I'm going to close it for now.
