### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by scottybo** [backup-manager/backup-manager#140]
There was a thread 4 years ago about encryption: https://github.com/backup-manager/backup-manager/issues/25

I was hoping this topic could be revisited with the upcoming GDPR regulations - encryption before sending to s3 etc would tick a large box for compliance.

Is this possible yet using backup-manager?

**Comment by ShawnMcCool** [comment]
I think that it just takes designing new tasks / procedures. If you look at the architecture it's pretty simple. Would you like to take a swing at it yourself? I could do some code reviews and help along the process if you'd like. Let me know and we could plan something out together.

**Comment by scottybo** [comment]
I'd love to help, but under mountains of work at the moment unfortunately :(

**Comment by ShawnMcCool** [comment]
Join the club, brother.
