### ISSUE TITLE
  french word mistake in the automatic email

### ISSUE THREAD

**Issue by RolandGautier** [backup-manager/backup-manager#141]
Hi,
One of the last lines of the french version email is :+1: "**Utilisanton** du fichier de configuration existant du client MySQL: /root/.backup-manager_my.cnf".
This must be :+1: "**Utilisation** du fichier de configuration existant du client MySQL: /root/.backup-manager_my.cnf.
It doesn't really matter, but why not correct it ?
Best regards,
Roland

**Comment by ShawnMcCool** [comment]
Hi, that has nothing to do with this project as far as I can tell. =)
