### ISSUE TITLE
Proposal 

### ISSUE THREAD

**Issue by raupie** [backup-manager/backup-manager#146]
I wanted to build something like backup-manager for my symfony based projects and you guys did a way better job than what I would have done. However, I was hoping for a few extra features and instead of rebuilding all of this myself I was thinking of adding the following functionality with your blessing.
1. Defining default filename in configuration
2. Symfony - custom command name i.e. (backup-manager:backup -> bm:backup)
3. Scripts - This would be the ability to chain commands together after the backup/import has been completed. Example: I would like to run another command to reindex my solr server and to clear the cache. The would avoid having to type several bin/console commands and chaining them together with && i.e. `bin/console backup-manager:backup default local -c gzip && bin/console cache:pool:clear cache.redis && bin/console solr:reindex` If that could be simplified into one command that would be fantastic. 

Looking forward to any feedback. Thanks.

**Comment by ShawnMcCool** [comment]
1. I basically just have scripts like this for everything:

**backup.php**
![image](https://user-images.githubusercontent.com/560749/58877382-d2d4ed00-86d0-11e9-9499-2f2e8314ca11.png)

2. I don't know anything about the symfony bits and what @Nyholm plans for them. Basically I want him to have as much autonomy to make decisions as possible.

3. I'm already doing this in my projects, but i'm using the code form and not the CLI tooling for that. See #1
