### ISSUE TITLE
mysqldump: unknown variable 'column-statistics=0'

### ISSUE THREAD

**Issue by kundancool** [backup-manager/backup-manager#154]
While dumping database getting error 

> Dumping database and uploading...
> 
>    BackupManager\ShellProcessing\ShellProcessFailed  : mysqldump: unknown variable 'column-statistics=0'
> 
this is caused by https://github.com/backup-manager/backup-manager/blob/9c7556e3e0ba46afcc32dc4e057dab491a71c3f0/src/Databases/MysqlDatabase.php#L44
commenting that line which adds "extraParams" => "--column-statistics=0"
fixes the issue is there a proper fix to it?

**Comment by ShawnMcCool** [comment]
This should be resolved.
