### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by Ahmed-Badawy** [backup-manager/backup-manager#166]
Fatal error: Uncaught BackupManager\ShellProcessing\ShellProcessFailed: Access is denied. in C:\xampp5\htdocs\testingBackup\vendor\backup-manager\backup-manager\src\ShellProcessing\ShellProcessor.php:22 Stack trace: #0 C:\xampp5\htdocs\testingBackup\vendor\backup-manager\backup-manager\src\Tasks\Database\DumpDatabase.php(41): BackupManager\ShellProcessing\ShellProcessor->process(Object(Symfony\Component\Process\Process)) #1 C:\xampp5\htdocs\testingBackup\vendor\backup-manager\backup-manager\src\Procedures\Sequence.php(29): BackupManager\Tasks\Database\DumpDatabase->execute() #2 C:\xampp5\htdocs\testingBackup\vendor\backup-manager\backup-manager\src\Procedures\BackupProcedure.php(66): BackupManager\Procedures\Sequence->execute() #3 C:\xampp5\htdocs\testingBackup\backup.php(11): BackupManager\Procedures\BackupProcedure->run('development', Array, 'gzip') #4 {main} thrown in C:\xampp5\htdocs\testingBackup\vendor\backup-manager\backup-manager\src\ShellProcessing\ShellProcessor.php on line 22

**Comment by ShawnMcCool** [comment]
You might need to install gzip on your windows.

I never really considered that it'd be used on Windows so I haven't tested it.

Try going to command line and typing "gzip" and see if there's a command installed or not.
