### ISSUE TITLE
CRITICAL SECURITY ALERT

### ISSUE THREAD

**Issue by markushausammann** [backup-manager/backup-manager#177]
https://github.com/thephpleague/flysystem/security/advisories/GHSA-9f46-5r25-5wfm

Please make a release with flysystem updated.

**Comment by xKZL** [comment]
@Nyholm  Is there any plan to switch to flysystem 3.0 ?

**Comment by Nyholm** [comment]
Of course we should. But we need to get @ShawnMcCool to share write access first. 

I cannot merge to this repo.
