### ISSUE TITLE
Standalone examples don't work

### ISSUE THREAD

**Issue by iantearle** [backup-manager/backup-manager#18]
Tried using examples, all I got was config expects an array - string given.

Got contents of files as array and got a little further, now have the following error:

Fatal error: Uncaught exception 'BigName\BackupManager\Config\ConfigNotFoundForConnection' with message 'Could not find configuration for connection local' in /Users/iantearle/Sites/TicketGun/vendor/heybigname/backup-manager/src/Config/Config.php:46 Stack trace: #0 /Users/iantearle/Sites/TicketGun/vendor/heybigname/backup-manager/src/Filesystems/FilesystemProvider.php(62): BigName\BackupManager\Config\Config->get('local', 'type') #1 /Users/iantearle/Sites/TicketGun/vendor/heybigname/backup-manager/src/Filesystems/FilesystemProvider.php(44): BigName\BackupManager\Filesystems\FilesystemProvider->getConfig('local', 'type') #2 /Users/iantearle/Sites/TicketGun/vendor/heybigname/backup-manager/src/Procedures/BackupProcedure.php(25): BigName\BackupManager\Filesystems\FilesystemProvider->get('local') #3 /Users/iantearle/Sites/TicketGun/base/backup.php(4): BigName\BackupManager\Procedures\BackupProcedure->run('development', 's3', 'test/backup.sql', 'gzip') #4 {main} thrown in /Users/iantearle/Sites/TicketGun/vendor/heybigname/backup-manager/src/Config/Config.php on line 46

**Comment by markushausammann** [comment]
Normally there is not such thing as a local database connection and a production database connection living in parallel. There is just THE environment specific database connection. I don't get why I should have to add a `local` database connection if I'm not going to use it.

**Comment by ShawnMcCool** [comment]
Are you sure that you're not talking about the Local storage configuration which allows Flysystem to access files locally using the same API as accessing them remotely?

**Comment by markushausammann** [comment]
I figured it out, I misunderstood before. It isn't completely clear from the documentation to say the least but once you figure it out, it all works fine.
