### ISSUE TITLE
Possibly add Rackspace "url" config option

### ISSUE THREAD

**Issue by mitchellvanw** [backup-manager/backup-manager#23]
I've noticed that currently we're hardcoding the "url" in the Rackspace client. Now, I personally don't use Rackspace and thus I can't make the correct call on this.

Does the Rackspace config need to have a "url" option?

For reference: https://github.com/heybigname/backup-manager/blob/master/src/Filesystems/RackspaceFilesystem.php#L30

I'd like some feedback on this.

Thanks

**Comment by mferrara** [comment]
@j0an did you ever find a solution about that issue?

I've tried several times to get rackspace working with this package and can't seem to do so...exact same credentials are working just fine with Flysystem.

**Comment by j0an** [comment]
Hi @mferrara

No, and I didn't try again :(




j.
