### ISSUE TITLE
is there any reason for not to automatically add the db_name + timestamp to the backup name?

### ISSUE THREAD

**Issue by j0an** [backup-manager/backup-manager#29]

**Comment by mrgodhani** [comment]
Looking forward for this feature too. But for now do we have any temporary solution ? I don't want to ssh in server everytime and do backup manually. Rather I would use scheduler to schedule backup every bi weekly or weekly basis.

**Comment by summerblue** [comment]
Here is how my implementation for auto-naming: https://gist.github.com/summerblue/e34f1c79e100c5deac20

**Comment by mrgodhani** [comment]
@summerblue awesome ! Thanks. 

I wish if they integrate in plugin itself though.

**Comment by JosephSilber** [comment]
@mrgodhani If you don't want to create your own artisan command, you can generate the date in your cron:

    php artisan db:backup --destinationPath=`date +\%Y-\%m-\%d`.sql

Fill in the other options as need...
