### ISSUE TITLE
Could not find configuration for connection

### ISSUE THREAD

**Issue by johannesfosseus** [backup-manager/backup-manager#36]
Hi

Have been using this great code for a while but suddenly I have this error, and the backups fail?

[BigName\BackupManager\Config\ConfigNotFoundForConnection]  
Could not find configuration for connection local-sitename

<?php
return [
    'local-sitename' => [
        'type' => 'mysql',
        'host' => 'localhost',
        'port' => '3306',
        'user' => 'root',
        'pass' => 'secret',
        'database' => 'mydatabase',
    ],
];

$now = strftime("%Y_%m_%d", strtotime("now"));
$manager = App::make('BigName\BackupManager\Manager');
$manager->makeBackup()->run(
    'local-sitename',
    'local',
    $now.'_mybck.sql',
    'gzip'
);

Trying to run this from my terminal
php artisan nightly --env=local-sitename

**Comment by pakkocool** [comment]
I have the same issue, but I couldn't make it work

$manager = App::make('BigName\BackupManager\Manager');
$manager->makeBackup()->run('development', 's3', 'backup.sql', 'gzip');

config/packages/heybigman/backup-manager/database.php

return [
    'development' => [
        'type' => 'mysql',
        'host' => 'localhost',
        'port' => '3306',
        'user' => 'forge',
        'pass' => 'secret',
        'database' => 'forge',
    ],
];

config/packages/heybigman/backup-manager/database.php
return [
    'local' => [
        'type' => 'Local',
        'root' => '/',
    ],
    's3' => [
        'type' => 'AwsS3',
        'key'    => 'keysecret',
        'secret' => 'keysecreet',
        'region' => Aws\Common\Enum\Region::US_EAST_1,
        'bucket' => 'mybucket',
        'root'   => '',
    ]
];

Someone can tell me what I'm doing wrong?

Thanks!
