### ISSUE TITLE
[ErrorException]   unlink(/vagrant/laravel/app/storage/backups/53eb70981e319.gz): Text file busy

### ISSUE THREAD

**Issue by cmosguy** [backup-manager/backup-manager#41]
@mitchellvanw @ShawnMcCool Firstly, I want to say thanks for working on this project, I really appreciate you helping streamline the process here.  

I am going to file a new issue for this as this message occurs every time I create a new backup:

[ErrorException]
  unlink(/vagrant/laravel/app/storage/backups/53eb70981e319.gz): Text file busy

Please advise on how to fix this please.

Thanks,
Adam

P.S. @ShawnMcCool Any new laravel.io podcasts coming up?

**Comment by JoelGross** [comment]
I am having this same issue... using homestead as my virtual machine on my dev box.

**Comment by ShawnMcCool** [comment]
Unfortunately, I don't have a homestead box. My guess is that the way homestead mounts the drive is causing some weirdness. I'm not sure how to troubleshoot this at the moment. Any ideas?
