### ISSUE TITLE
RequestTimeTooSkewedException on backup

### ISSUE THREAD

**Issue by nicekiwi** [backup-manager/backup-manager#59]
I get this when I try to run a backup.
                                                                              
  [Aws\S3\Exception\RequestTimeTooSkewedException]                            
  The difference between the request time and the current time is too large.

From start to finish, it takes about 10secs to make the commands. 

The gzip'd sql files are only 8KB. 

My VM is running a different timezone to that of my project, if that makes any difference. 
                                                                              
		vagrant@homestead:~/www/ag-aus$ php artisan db:backup
		These arguments haven't been filled yet: database, destination, destinationPath, compression
		The following questions will fill these in for you.

		Available database connections: sqlite, mysql, pgsql, sqlsrv
		From which database connection you want to dump?mysql

		Available storage services: local, s3, rackspace, dropbox, ftp, sftp
		To which storage service you want to save?s3

		How do you want to name the backup? mysql-backups/ag-aus-local.sql

		Available compression types: null, gzip
		Which compression type you want to use?gzip

		Just to be sure...
		Do you want to create a backup of mysql, store it on s3 at mysql-backups/ag-aus-local.sql and compress it to gzip?

		Are these correct? [Y/n] y
		Dumping database and uploading...

		                                                                              
		  [Aws\S3\Exception\RequestTimeTooSkewedException]                            
		  The difference between the request time and the current time is too large.  
		                                                                              

		db:backup [--database[="..."]] [--destination[="..."]] [--destinationPath[="..."]] [--compression[="..."]]

From my logfile:

    [2015-02-02 14:00:18] local.ERROR: Aws\S3\Exception\RequestTimeTooSkewedException: AWS Error Code: RequestTimeTooSkewed, Status Code: 403, AWS Request ID: ABE3226CE02932DC, AWS Error Type: client, AWS Error Message: The difference between the request time and the current time is too large., User-Agent: aws-sdk-php2/2.7.17 Guzzle/3.9.2 curl/7.35.0 PHP/5.5.15RC1 [] []

**Comment by nicekiwi** [comment]
Ok, so I added a script to my Homestead provisioning to set my timezone correctly and setup local and production timezones in my project and it works fine. 

However, the production server will be located in the US, but running my local timezone NZ and the application timezone will be AUS, so this will still be an issue in production.

It seems that the command to backup to S3 takes the time from the application and the time from the environment, somehow. Could the the backup-manager be modified to only use one timezone for its transactions, rather than both?

**Comment by ShawnMcCool** [comment]
Hmm. I don't use homestead but I've never run the backup-manager without being inside a Vagrant VM. My intuition is that this is a configuration problem.
