### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by CodeSkills** [backup-manager/backup-manager#61]
Hello,

just wanted to ask since L5 ->package() has been removed. Are you planing to rewrite laravel service provider to support Laravel 5?

Thanks!

**Comment by cmosguy** [comment]
@ShawnMcCool just wanted to ask the same thing. Is this good to go for Laravel 5?

**Comment by barryvdh** [comment]
Perhaps better to seperate integrations to a different package? That way the integration can be updated without having to change the standalone package.

**Comment by cmosguy** [comment]
Hey @barryvdh , coincidentally, I studied your updates for IdeHelper [here](https://github.com/barryvdh/laravel-ide-helper/blob/master/src/IdeHelperServiceProvider.php) to navigate my way to update for Laravel 5.

If you can, take a look at this [PR](https://github.com/heybigname/backup-manager/pull/66).  I went ahead and made a new service provider specifically for Laravel 5.  I updated the readme in the package here in this [section](https://github.com/cmosguy/backup-manager/tree/laravel5#laravel-5).  If you want to test this out you can create a composer `package.json` with the following:

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/cmosguy/backup-manager"
        }

    ],
    "require": {
        "heybigname/backup-manager": "dev-laravel5",
        "league/flysystem-aws-s3-v2": "~1.0",
        "league/flysystem-dropbox": "~1.0",
        "league/flysystem-rackspace": "~1.0@dev",
        "league/flysystem-sftp": "~1.0@dev"
    }
```

Any expert advice from you would be greatly appreciated.

Cheers!
Adam

**Comment by bajramemini** [comment]
Any update on the L5 Support?

**Comment by cinek19** [comment]
Still not working on L5?

**Comment by ShawnMcCool** [comment]
I released a new version of this package with no laravel support. laravel drivers have been added as separate repositories inside the backup-manager organization.

https://github.com/backup-manager

Laravel 4 support is working in this way. composer require backup-manager/laravel-4

I'd like to get 5 support in there next.

**Comment by ShawnMcCool** [comment]
Ok, I put Laravel 4 and 5 together in the backup-manager/laravel repo. Laravel 5 has a service provider that may need a few tweeks.

**Comment by cmosguy** [comment]
@ShawnMcCool, i've already figured it out for your you, did you see my PR with the original bigname package?

**Comment by cmosguy** [comment]
@ShawnMcCool never mind, sorry, I just saw the other thread on your response, please ignore my previous message.   

Thanks!

**Comment by ShawnMcCool** [comment]
@cmosguy thanks for all of your work. The Laravel 5 support that you added was put into the backup-manager/laravel package.
