### ISSUE TITLE
Laravel 4.2 issue: Could not find configuration for connection local

### ISSUE THREAD

**Issue by aligajani** [backup-manager/backup-manager#67]
I am getting this error while doing db:backup on the command line.

 [BigName\BackupManager\ShellProcessing\ShellProcessFailed]  
  sh: /550204f755e4b: Permission denied  

I am expecting the package to get my local settings. It's not. Help.

**Comment by ShawnMcCool** [comment]
You have a permission problem, what does your configuration look like?

**Comment by jakeryansmith** [comment]
I'm having the same issue. If I run the artisan command with sudo it's fine, but any other way I get the same "Permission denied" message.

**Comment by jakeryansmith** [comment]
Never mind I figured it out. I needed to change the root path for the local configuration to a folder with write permissions.
