### ISSUE TITLE
How do I append a timestamp to a backup filename in Backup Manager?

### ISSUE THREAD

**Issue by aligajani** [backup-manager/backup-manager#69]

**Comment by ShawnMcCool** [comment]
In the place where you define the filename, use PHP code to add a date in, or if doing it on the command line, use bash.

**Comment by aligajani** [comment]
Used bash, thanks.

On Mon, Apr 13, 2015 at 2:22 PM, Shawn McCool <notifications@github.com>
wrote:

> In the place where you define the filename, use PHP code to add a date in,
> or if doing it on the command line, use bash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heybigname/backup-manager/issues/69#issuecomment-92288617>
> .
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com
