### ISSUE TITLE
[BadMethodCallException] Call to undefined method [package]

### ISSUE THREAD

**Issue by mms-hamburg** [backup-manager/backup-manager#72]
After adding Service Provider i get:

[BadMethodCallException]            
  Call to undefined method [package]

any idea?

**Comment by GrahamCampbell** [comment]
Yes, Laravel 5 is not supported.

**Comment by RomainSauvaire** [comment]
Is it planned to be @GrahamCampbell  and if so, do you have any timeframe ?

**Comment by mms-hamburg** [comment]
+1

**Comment by GrahamCampbell** [comment]
> do you have any timeframe ?

Nothing to do with me, :)

**Comment by RomainSauvaire** [comment]
Thanks Graham ;)

**Comment by frankmichel** [comment]
@ShawnMcCool any plans/timeframe for laravel5 support?

**Comment by ShawnMcCool** [comment]
@frankmichel Yes, I have change the way that the package is being provided. It's all in early phases now. 

https://github.com/backup-manager

But, I would absolutely appreciate some help. Currently, I'm working on getting the backup-manager/laravel-4 package working. Once that happens, I'm going to mark it 1.0 and mark the backup manager (with the laravel 4 stuff removed) as 1.0.

Then, I'll get the laravel-5 package up and running.

Again, any help would be appreciated. =)
