### ISSUE TITLE
Composer link dead

### ISSUE THREAD

**Issue by myjeux** [backup-manager/backup-manager#75]
Hi,
Since you change the repository from heybigname to backup-manager, composer has been broken.
Thanks,

**Comment by GrahamCampbell** [comment]
Should still work.

**Comment by GrahamCampbell** [comment]
GitHub forwards requests to the old repo to the new one.

**Comment by myjeux** [comment]
Installing heybigname/backup-manager (0.3.10)
    Downloading: Connecting...    Failed to download heybigname/backup-manager from dist: The "https://api.github.com/repos/heybigname/backup-manager/zipball/ad37136d7de3ed33b15f1c8dfa6f6a03fbfc07a4" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by GrahamCampbell** [comment]
Ahhh, GitHub are fixing that soon. https://developer.github.com/changes/2015-05-26-repository-redirects-are-coming/.

**Comment by GrahamCampbell** [comment]
I don't have access to packagist to fix this. Ping @ShawnMcCool.

**Comment by GrahamCampbell** [comment]
You should still be able to install this though, because on download failure, composer will clone the repo instead.

**Comment by ShawnMcCool** [comment]
What's your packagist name?

**Comment by ShawnMcCool** [comment]
Found it.

**Comment by ShawnMcCool** [comment]
Pointed packagist to new repo.
