### ISSUE TITLE
Packagist Name

### ISSUE THREAD

**Issue by ShawnMcCool** [backup-manager/backup-manager#77]
@GrahamCampbell is it possible to somehow migrate to the packagist package backup-manager/backup-manager instead of heybigname/backup-manager without breaking everyone's installs? 

I don't care if we lose install statistics or anything else.

**Comment by GrahamCampbell** [comment]
@ShawnMcCool Best way is to copy this repo somewhere else and point the original package to it. Then rename this one and publish it on packagist again.

**Comment by ShawnMcCool** [comment]
So, for example.. Perhaps I fork this package to heybigname/backup-manager (where it's originally from) and then change this repo's composer.json to have the name backup-manager/backup-manager, then I add this repository to packagist and mark the old package as 'abandoned' with a link to this one?

**Comment by GrahamCampbell** [comment]
Yeh, that works. :)

**Comment by GrahamCampbell** [comment]
If I were you i'd reset this fork to remove the 1.0 stuff.

**Comment by ShawnMcCool** [comment]
Could you elaborate on what you mean by that?

**Comment by GrahamCampbell** [comment]
Do a hard reset on the master to the last 0.3.x tag on the fork and delete the 1.x tags.

**Comment by ShawnMcCool** [comment]
K

**Comment by ShawnMcCool** [comment]
Ok, @GrahamCampbell I think that this is done.

**Comment by GrahamCampbell** [comment]
You should probably delete all other other branches from the fork too. :)

**Comment by ShawnMcCool** [comment]
Done

**Comment by GrahamCampbell** [comment]
:)
