### ISSUE TITLE
mysqldump path in config

### ISSUE THREAD

**Issue by mediademo** [backup-manager/backup-manager#79]
Have to hard-code the full (non-default) mysqldump path when running locally. Works fine in terminal, but not through app. Would be good to have an option in config.

**Comment by ShawnMcCool** [comment]
The user that executes the script needs to have their environment variables properly configured. This is why you can run it in your shell with it working correctly.

**Comment by mediademo** [comment]
Env variables proved fruitless for me, I'm just gonna blame MAMP ;)  a symlink solved it:
sudo ln -s /Applications/MAMP/Library/bin/mysqldump /usr/local/bin/mysqldump
Cheers
