### ISSUE TITLE
Google Cloud Storage Support

### ISSUE THREAD

**Issue by bcalik** [backup-manager/backup-manager#84]
Hello,

Google Cloud Storage support should be easy to implement since it uses the exact same protocol with AwsS3.

Please check this out:
https://github.com/thephpleague/flysystem/issues/448#issuecomment-81921872

**Comment by bcalik** [comment]
@ShawnMcCool I have implemented it and works well.
Please checkout my fork. You can cherry-pick the commit from my fork.

backup-manager:
https://github.com/bcalik/backup-manager/commit/d4ae5502b556b2deaaef08d47f4b688edaa664d8
laravel:
https://github.com/bcalik/laravel/commit/2917347ffdb991f545c85e91efaef4139ef0284a

**Comment by bcalik** [comment]
Here is a pull request:
https://github.com/backup-manager/backup-manager/pull/89

I have been using it for 2 months without any problem.

**Comment by ShawnMcCool** [comment]
Thanks man. =) Merged.
