### ISSUE TITLE
Packagist requires out of date?

### ISSUE THREAD

**Issue by warksit** [backup-manager/backup-manager#86]
Packagist (https://packagist.org/packages/backup-manager/backup-manager#1.0.7) 
<img width="1160" alt="screen shot 2015-09-11 at 12 08 08" src="https://cloud.githubusercontent.com/assets/5296633/9813485/d3faacc2-587d-11e5-80d6-43e4342f25d9.png">
is showing aws/aws-sdk-php ~2.4 is required yet github correctly shows ~3.0. This is causing me to get "Your requirements could not be resolved to an installable set of packages."

**Comment by jakeryansmith** [comment]
I'm having the same issue. I can't install backup-manager/laravel and league/flysystem-aws-s3-v3 at the same time because they require different version on the aws/aws-sdk-php.

**Comment by warksit** [comment]
As a temp workaround add the following to your composer.json:
''''
	"backup-manager/backup-manager": "dev-master@dev",
''''

**Comment by jakeryansmith** [comment]
Awesome thanks!

**Comment by jakeryansmith** [comment]
Unfortunately the Laravel driver still pulls in the 1.* branch.

**Comment by ShawnMcCool** [comment]
Hello, I just added a version update that hopefully resolves this.

https://packagist.org/packages/backup-manager/backup-manager#1.0.8

Let me know what you think.

**Comment by jakeryansmith** [comment]
@ShawnMcCool Just tried it and it works for me. Thanks!

**Comment by ShawnMcCool** [comment]
Great, I'm going to close this issue then. Let me know if anything doesn't look on the up and up.
