### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by bcalik** [backup-manager/backup-manager#90]
Hello,

I have a large database and backup manager timeouts while running the process.

```shell
  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "mysqldump --routines --host='localhost' --port='3306' --user='**' --password='**' 'arsiv' > '
  /var/www/arsiv/app/storage/backups/56465d6a4c759'" exceeded the timeout of 60 seconds.
```

I have already increased the timeouts from php.ini, but it does not solve.
What can I do?

Thanks.

**Comment by bcalik** [comment]
It looks like the default timeout of Symfony Shell Process is 60.

There is a method to set timeout. Setting this value to null before running the command will solve the problem. I will try and make a pull request.

**Comment by ShawnMcCool** [comment]
This should be resolved. Thanks .=)
