### ISSUE TITLE
Dump all database for user

### ISSUE THREAD

**Issue by barryvdh** [backup-manager/backup-manager#93]
Instead of backing up each single user, I'd like to dump multiple databases at once (eg for the entire VPS or certain user).
Would this be something to add as a Pull Request, or would you suggest creating a script that lists all the database, and then runs the `makeBackup()` task on each of them?

Could just use the mysql CLI; 
`mysql --host=%s --port=%s --user=%s --password=%s -e "SHOW DATABASES" -B -N`

**Comment by ShawnMcCool** [comment]
I think that it might make sense to have a procedure called like BackupAllDatabasesProcedure or something.

Looping over makeBackup() or whatever sounds reasonable to me as well.
