### ISSUE TITLE
Permission Denied error

### ISSUE THREAD

**Issue by anandatheerthan** [backup-manager/backup-manager#95]
I copied the example provided but getting the error below. Have given 777 permission.

\nFatal error: Uncaught exception 'BackupManager\ShellProcessing\ShellProcessFailed' with message 'sh: 1: cannot create /567d3a4664faa: Permission denied
\n' in /usr/share/nginx/html/htdocs/dbback/vendor/backup-manager/backup-manager/src/ShellProcessing/ShellProcessor.php:35\nStack trace:\n#0 /usr/share/ngin
x/html/htdocs/dbback/vendor/backup-manager/backup-manager/src/Tasks/Database/DumpDatabase.php(35): BackupManager\ShellProcessing\ShellProcessor->process(
)\n#1 /usr/share/nginx/html/htdocs/dbback/vendor/backup-manager/backup-manager/src/Procedures/Sequence.php(27): BackupManager\Tasks\Database\DumpDatabas
e->execute()\n#2 /usr/share/nginx/html/htdocs/dbback/vendor/backup-manager/backup-manager/src/Procedures/BackupProcedure.php(57): BackupManager\Procedures
\Sequence->execute()\n#3 /usr/share/nginx/html/htdocs/dbback/backup.php(3): BackupManager\Procedures\BackupProcedure->run()\n#4 {main}

**Comment by GrahamCampbell** [comment]
> I copied the example provided but getting the error below. Have given 777 permission.

Well, the error says otherwise.

**Comment by anandatheerthan** [comment]
thanks but what permission should I give and where?

**Comment by GrahamCampbell** [comment]
try 775 -R

**Comment by anandatheerthan** [comment]
I have given chmod -R 775 to all directories including root where the files are placed.  Still getting the same error.

**Comment by anandatheerthan** [comment]
<?php
$manager = require 'bootstrap.php';
$manager->makeBackup()->run('student', 'dropbox', 'test\backup.sql', 'gzip');
var_dump($manager);

This is what I use in my backup.php

**Comment by mitchellvanw** [comment]
@anandatheerthan were you able to make a backup?

**Comment by anandatheerthan** [comment]
No, I still face the same error. If I use this package with laravel then it works fine. But if I try to use as standalone I get this permission denied error. 

Regards,
Anand

**Comment by mitchellvanw** [comment]
@anandatheerthan Are you setting these permissions in your VM or host machine?
