### ISSUE TITLE
FileExistsException in Filesystem.php

### ISSUE THREAD

**Issue by xav13** [backup-manager/backup-manager#97]
Hello, 

I used your script on different website and works Well thank you!
On a single one i have a problem : FileExistsException in Filesystem.php line 395:
File already exists at path: 5693d2350eb67test.sql.gz
(this is exactly the same code on each website)

I have implemented your script in a silex / Symfony application.

Do you have any idea ?
Maybe about server configuration, folder permission...

Thank you very much to help me. Sorry for my bad english ;)

**Comment by mitchellvanw** [comment]
@xav13 Have you had this issue ever since?
